version: '3.7'

services:
  # Express Server
  nodejs:
    # image: webapp-server
    build: 
      context: ./api
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "80:8080"
    volumes:
      - ./api:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    # depends_on:
    #    - mongodb


  # # REACT client 
  # client:
  #   # image: webapp-client:latest
  #   build: 
  #     context: ./client
  #     dockerfile: Dockerfile
  #   image: webapp-client
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./client:/var/www/app
  #   links:
  #     - api
  #   networks: 
  #     - webappnetwork
  
  # Mongodb database
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    #   ports:
    #   - 27017:27017
    # command: mongod --noauth --smallfiles
    # networks:
    #   - webappnetwork

  networks:
    app-network:
      driver: bridge
   
  volumes: 
    dbdata:
    node_modules:
    
  # # Nginx Load Balancer
  # nginx:
  #   image: nginx:1.13.3-alpine
  #   container_name: Nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - client
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d/default.conf:ro
  #       #   - web-root:/var/www/html
  #   #   # - certbot-etc:/etc/letsencrypt
  #   #   # - certbot-var:/var/lib/letsencrypt
  #   networks:
  #     - webappnetwork

# Letsencrypy certbot configurations
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email sammy@example.com --agree-tos --no-eff-email --staging -d example.com  -d www.example.com 

  

# volumes:
#   certbot-etc:
#   certbot-var:
#   web-root:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/sammy/node_project/views/
#       o: bind

